# Utiliza la imagen oficial de MySQL desde Docker Hub
FROM mysql:latest

# Establece las variables de entorno necesarias
ENV MYSQL_ROOT_PASSWORD=l!-@Aq2FvE3p
ENV MYSQL_DATABASE=ARDEP
ENV MYSQL_USER=user01
ENV MYSQL_PASSWORD=USER01USER01

# Copia scripts SQL o archivos de configuración si es necesario (usado para crear las tablas la primera vez)
COPY ./scripts/ /docker-entrypoint-initdb.d/

# Expone el puerto de MySQL (por defecto, es el puerto 3306)
EXPOSE 3306

